### ISSUE TITLE
add `from_just`

### ISSUE THREAD

**Issue by stla** [armcn/maybe#3]
Hello,

  In Haskell there is the `fromJust` function. I find it useful. In your package it would be:

```r
from_just <- function(x){
  if(is_just(x)){
    x[["content"]]
  }else{
    stop("`x` is not a 'Just' value.")
  }
}
```

Cheers.

**Comment by armcn** [comment]
Thanks, I'll add this in the next release. Are there other Haskell functions that you think would be useful when working with maybes?

**Comment by stla** [comment]
`catMaybes` and `mapMaybe`:

```r
library(maybe)

catMaybes <- function(list_of_maybe_values){
  lapply(Filter(is_just, list_of_maybe_values), `[[`, "content")
}

catMaybes(list(just(1), nothing(), just("a")))
# [[1]]
# [1] 1
# 
# [[2]]
# [1] "a"

mapMaybe <- function(list_of_ordinary_values, f){
  catMaybes(lapply(list_of_ordinary_values, f))
}

mapMaybe(list(4, 9, -1, "a"), maybe(sqrt))
# [[1]]
# [1] 2
# 
# [[2]]
# [1] 3
```

**Comment by armcn** [comment]
Thanks for the suggestions. I added from_just, filter_justs (alias cat_maybes), filter_map (no alias because sounds too much like maybe_map). The changes won't be on CRAN for at least a month, let me know if you have any other suggestions before that time.

**Comment by stla** [comment]
Also `liftA2` for binary functions:

```r
liftA2 <- function(f, x, y){
  if(is_just(x) && is_just(y)){
    just(f(x[["content"]], y[["content"]]))
  }else{
    nothing()
  }
}

liftA2(`+`, just(2), just(3))
# Just
# [1] 5
```

**Comment by armcn** [comment]
I added `maybe_map2` to fit with `maybe_map`. I could add `maybe_map3` ... `map5` but that seems rare someone would need those in R. I'm going to keep the Haskell aliases limited to `fmap`, `bind`, `join`, `from_maybe` for now.

**Comment by stla** [comment]
Hmmm `maybe_map_n` would be a "`maybe do.call`" no?

```r
maybe_do.call <- function(what, args){
  are_just <- all(vapply(args, is_just, logical(1L)))
  if(are_just){
    just(do.call(what, lapply(args, `[[`, "content")))
  }else{
    nothing()
  }
}
```

**Comment by armcn** [comment]
Yeah that's true. I'm going to leave it out for now unless someone has a compelling use-case. I want to keep the package relatively minimal for now and see if it can get any traction before adding more utility functions.

**Comment by stla** [comment]
Hi armcn,

 FYI I've done [a package](https://github.com/stla/Either) which imports yours. This is the 'Either' type.
